name: Cowsay Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_cowsay:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le code source
        uses: actions/checkout@v2

      - name: Installer cowsay
        run: sudo apt-get install -y cowsay

      - name: Exécuter cowsay
        run: |
          echo "Hello from GitHub Actions!" | cowsay
